name: 🚀 Feature Request
description: Suggest a new feature or enhancement for EchoTrail
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees:
  - KentHenriks1
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        We love hearing your ideas! Please describe your feature request in detail.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - AI & Storytelling
        - Maps & Navigation
        - User Experience
        - Audio & TTS
        - Performance
        - Accessibility
        - Social Features
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Really needed
        - Critical - Blocking usage
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a user, I want... because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or features you've considered

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: Any visual aids, mockups, or screenshots (drag & drop images here)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information about the feature

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check any that apply
      options:
        - label: This might require changes to the AI pipeline
        - label: This affects the mapping system
        - label: This needs new UI components
        - label: This requires backend/database changes
        - label: This impacts performance
        - label: I'm willing to help implement this